sample-keys/rpm_keys: update sample keys
Issue: LIN1025-6709

RHEL 10's enhanced security policies reject keys using the weak
encryption algorithms (like SHA-1), which was causing build failures:

ERROR: secure-core-image-initramfs-1.0-r0 do_rootfs: Importing GPG key failed. Command
'/build/tmp/work/intel_x86_64-wrs-linux/secure-core-image-initramfs/1.0/recipe-sysroot-native/usr/bin/rpmkeys
--root=/build/tmp/work/intel_x86_64-wrs-linux/secure-core-image-initramfs/1.0/rootfs --import
/build/tmp/work/intel_x86_64-wrs-linux/secure-core-image-initramfs/1.0/secure-core-image-initramfs-1.0/rpm-key' returned 1:
error: Certificate CFA856DFC7CB87BE:
  Policy rejects CFA856DFC7CB87BE: No binding signature at time 2025-12-23T15:51:34Z
error: /build/tmp/work/intel_x86_64-wrs-linux/secure-core-image-initramfs/1.0/secure-core-image-initramfs-1.0/rpm-key: key 1 import failed.

The sq-keyring-linter tool detected that the current key uses SHA-1:
$ sq-keyring-linter RPM-GPG-KEY-Wind-River-Linux-Sample
Certificate CFA856DFC7CB87BE is not valid under the standard policy: No binding signature at time 2025-12-26T09:40:41Z
Certificate CFA856DFC7CB87BE contains a User ID ("Wind-River-Linux-Sample (RPM Signing Certificate) <svc-linux@gmail.com>") protected by SHA-1

Update key to deprecate SHA1 algorithm. The new key was generated using
the following command:
$ create-user-key-store.sh -c "RPM Signing Certificate" \
  -n Wind-River-Linux-Sample -bn Wind-River-Boot-Sample \
  -m support@windriver.com -rp windriver

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>