wrlinux: Correct the Upstream-Status
Issue: LINCD-2473

Fixes:
   INFO: Traceback (most recent call last):
     File "/build/layers/oe-core/scripts/lib/checklayer/cases/common.py", line 87, in test_patches_upstream_status
       self.assertEqual(len(patches), 0 , \
   AssertionError: 1 != 0 : Found following patches with malformed or missing upstream status:
/build/layers/wrlinux/dynamic-layers/openembedded-layer/recipes-benchmark/lmbench/lmbench-3.0-a9/lmbench-3.0-a9_wr_integration.patch

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>