wrlinux-image-initramfs: Set IMAGE_NAME_SUFFIX to empty
Issue: LINCD-12969 LINUXEXEC-29606

After the below commit introduced in oe-core:
26d97acc71 image-artifact-names: include ${IMAGE_NAME_SUFFIX} directly in both ${IMAGE_NAME} and ${IMAGE_LINK_NAME}

We need to explicity set IMAGE_NAME_SUFFIX to empty to avoid using
the .rootfs IMAGE_NAME_SUFFIX to fix below issue:
ERROR: wrlinux-image-std-1.0-r5 do_bootimg: /build/tmp-glibc/deploy/images/intel-x86-64/wrlinux-image-initramfs-intel-x86-64.cpio.gz is invalid. initrd image creation failed.

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>