conf/gen-vendor-revision.conf: avoid skipping libgfortran
Issue: LINUXEXEC-32892

Set FORTRAN so that libgfortran is not skipped. Otherwise,
building libgfortran will have error like below:

  ERROR: QA Issue: libgfortran: LIC_FILES_CHKSUM points to an invalid file:
  TOPDIR/tmp-glibc/work-shared/gcc-13.3.0-r0.vr2400/gcc-13.3.0/COPYING.RUNTIME [license-checksum]

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>