enable-vendor-revision.bbclass: Use RecipeTaskPreProcess to append VR to PR
Issue: LINCD-21929

So that the SRCREV set in anonymous function will work.

Fixed errors like:
* Remove 'SRCREV=' from pseudo_git.bb
* Add the following lines in pseudo_git.bb:
  python() {
      d.setVar('SRCREV', '28dcefb809ce95db997811b5662f0b893b9923e0')
  }

* $ bitbake -p
  Fixed errors like:
  Exception: bb.fetch2.FetchError: Fetcher failure for URL: 'git://git.yoctoproject.org/pseudo;branch=master;protocol=https'. Please set a valid SRCREV for url [snip].

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>