wrlinux: fix yocto-check-layer error regarding ostree contents
Issue: LINCD-18419

The ostree bbappend file needs to be in dynamic-layers, and the
initramfs-ostree.bb which depends on ostree also needs to be there
too. Otherwise, yocto-check-layer will report the following error:

  ERROR: No recipes in default available for:
  /.../layers/wrlinux/recipes-extended/ostree/ostree_%.bbappend

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>