wrlinux-installer.conf: require wrlinux-graphics.conf
...
ERROR: Nothing RPROVIDES 'python3-blivetgui' (but layers/meta-anaconda/recipes-installer/anaconda/python3-anaconda_42.27.11.bb RDEPENDS on or otherwise requires it)
python3-blivetgui was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'python3-blivetgui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-blivetgui']
NOTE: Runtime target 'python3-anaconda' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-anaconda', 'python3-blivetgui']
NOTE: Runtime target 'lib32-wrlinux-image-installer' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-wrlinux-image-installer', 'wrlinux-image-installer', 'python3-anaconda', 'python3-blivetgui']
ERROR: Required build target 'wrlinux-image-installer' has no buildable providers.
Missing or unbuildable dependency chain was: ['wrlinux-image-installer', 'python3-anaconda', 'python3-blivetgui']
...

Require wrlinux-graphics.conf which adds x11 to DISTRO_FEATURES

Issue: LINUXEXEC-34734

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>