qtbase: install sqlite plugin for qt-example
Issue: LINCD-12734

The sqlite plugin is required by localstorageexample.
```
$ /usr/share/examples/quick/localstorage/bin/localstorageexample
qt.sql.qsqldatabase: QSqlDatabase: QSQLITE driver not loaded
qt.sql.qsqldatabase: QSqlDatabase: available drivers:
qrc:/qt/qml/localstorage/Database.js:6: Error: SQL: Cannot open database
```
wrlinux using feature to contorl the qt examples, so add the sqlite
plugin default when enable the qt-example.

Signed-off-by: Peng Zhang <peng.zhang1.cn@windriver.com>