wrlinux-recipelists: add libdecor support
Issue: LINUXEXEC-34654

When building nxp-ls1046 BSP, there is below error:
ERROR: Required build target 'wrlinux-image-std' has no
buildable providers.
Missing or unbuildable dependency chain was:
['wrlinux-image-std', 'nativesdk-packagegroup-sdk-host',
'nativesdk-qemu', 'nativesdk-libsdl2', 'nativesdk-libdecor']
So, add add libdecor support.

Signed-off-by: Meng Li <Meng.Li@windriver.com>