feature/docker: add seccomp and ipv6 in DISTRO_FEATURES
Issue: LIN1025-1474

Due to commit f9ba743dad69 ("docker: check for seccomp and ipv6") in
meta-virtualization layer, "seccomp" and "ipv6" become required distro
features of docker-moby who provides docker.

Fix:
ERROR: Nothing RPROVIDES 'docker'
docker-moby RPROVIDES docker but was skipped: missing required distro
features 'ipv6 seccomp' (not in DISTRO_FEATURES)

Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>